version: '3.8'

services:
  webapi:
    build:
      context: './BackendTest'
    ports:
      - 8082:8082
    depends_on:
      - postgredb
    networks:
      - mynetwork
  postgredb:
    image: postgres:13.11-alpine3.18
    env_file:
      - './envfiles/postgresql.env'
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - mynetwork
volumes:
  db-data:
    driver: local
networks:
  mynetwork:

